# Generated by Django 5.1 on 2024-08-14 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('notes', models.TextField()),
                ('lead', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('is_rejected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('happened_at', models.DateField()),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.position')),
            ],
        ),
    ]
