# Generated by Django 5.1 on 2024-08-14 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='notes',
        ),
        migrations.AlterField(
            model_name='note',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='jobs.position'),
        ),
    ]
