# Generated by Django 5.1 on 2024-08-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_position_notes_alter_note_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
