# Generated by Django 5.1.6 on 2025-11-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_position_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
